security:
  basic:
    enabled: false # turn off securing the app

management:
  security:
    enabled: false #turn off securing actuator endpoints

logging:
  level:
    io:
      pivotal: INFO

greeting:
  displayFortune: true

quoteServiceURL: http://quote-service-dev.cfapps.io/quote
